"""
Thin wrapper around the OpenAI Chat Completions API.

Every other module in this project calls `call_llm(...)` instead of
importing the OpenAI SDK directly. That gives us one place to:
  - plug in the API key / model name from config
  - handle API errors consistently
  - swap in a mock response for offline testing (MOCK_LLM=true)
"""

import logging
import time

from openai import OpenAI, OpenAIError

from src import config

logger = logging.getLogger(__name__)

_client = None


def get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(api_key=config.OPENAI_API_KEY)
    return _client


def call_llm(
    system_prompt: str,
    user_prompt: str,
    json_mode: bool = False,
    retries: int = 2,
    mock_kind: str = "extraction",
) -> str:
    """
    Send a system + user prompt to the configured chat model and return
    the raw text response.

    If MOCK_LLM is enabled in the environment, no network call is made at
    all -- a simple placeholder string is returned instead, so the rest
    of the workflow can still be exercised end to end. `mock_kind` tells
    the mock which shape of JSON to return ("extraction" or "summary"),
    since the two steps use different schemas.
    """
    if config.MOCK_LLM:
        return _mock_response(json_mode, mock_kind)

    client = get_client()
    last_error = None

    for attempt in range(1, retries + 2):
        try:
            response = client.chat.completions.create(
                model=config.OPENAI_MODEL,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format={"type": "json_object"} if json_mode else {"type": "text"},
                temperature=0.2,
            )
            return response.choices[0].message.content

        except OpenAIError as exc:
            last_error = exc
            logger.warning("LLM call failed (attempt %d/%d): %s", attempt, retries + 1, exc)
            time.sleep(1.5 * attempt)  # simple backoff before retrying

    # All retries used up -- let the caller decide how to handle this.
    raise RuntimeError(f"LLM call failed after {retries + 1} attempts: {last_error}")


def _mock_response(json_mode: bool, mock_kind: str) -> str:
    """A canned response used only when MOCK_LLM=true, for offline testing."""
    if not json_mode:
        return (
            "This is a placeholder response generated by MOCK_LLM mode. "
            "Set MOCK_LLM=false and provide a real OPENAI_API_KEY to see actual model output."
        )

    if mock_kind == "summary":
        return (
            '{"case_overview": "Mock case overview generated in offline test mode.", '
            '"key_issue": "Placeholder issue.", '
            '"action_taken": "None yet", '
            '"current_status": "Open", '
            '"recommended_next_action": "Assign to a support agent for review."}'
        )

    # default: extraction-shaped mock response
    return (
        '{"customer_name": "Mock Customer", "email": "mock@example.com", '
        '"phone_number": "0000000000", "complaint_category": "General", '
        '"issue_description": "This is placeholder text generated by mock mode.", '
        '"resolution_provided": "None provided", "is_complaint": "Yes", '
        '"escalation_required": "No", "supporting_document_available": "No", '
        '"overall_case_status": "Open"}'
    )
